### ISSUE TITLE
HTTP error for configuration

### ISSUE THREAD

**Issue by larrycai** [gangsta/jenkins-prometheus-grafana#1]
-  I installed the jenkins plugin and got the http://<jenkins server>/prometheus/ working
-  I configured it in grafana to add data source with above link

But after I added and "Save and test", it shows HTTP error, any suggestion?

**Comment by gangsta** [comment]
Hi @larrycai 

I would like to get little more info,

you can get logs from vagrant
```
vagrant ssh
sudo su
docker ps
```
select grafana docker

```
docker logs -f abovegrafanadocker
```

As 2ndary what if you refresh page of grafana ?

Greetings

**Comment by gangsta** [comment]
As addition maybe this Blog-post can help to get little more info:
https://medium.com/@gangsta_black/grafana-cool-dashboard-for-monitoring-jenkins-with-prometheus-c7ba4f1c6297

**Comment by larrycai** [comment]
aha, I made a mistake, I need grafana point to prometheus server (as datasource), and prometheus server has target to jenkins which that url needs to be there.

ok now, looks so nice.!
